In [1]:
# n=list(map(str,input("enter").split()))
# sum=0
# for i in n:
#     x=int(i[1])
#     sum+=x
#     print(sum)

## Data analysis
- any useful informtion is called as data
- types of data in devices
- .txt,.img,.ppt,.mp3,.excel,.docetc
 types of data in real time
1. quantitatve data
 -presents the size/volume of data
- screte and continous
- discrete:data is constant/fixed
 ex:nubers in dice,color,nationality etc
 - continous data means the value/data is continous 
 ex:data submission in feed fack form
 
 
- Data in Statatics
-  nominal,ordinal,interval and ratio
- NOMINAL: data is categorised on the basis of names
  - ex: color,nationality,gender
- ORDINAL:data is categorised upon the value
   - ex: feedback forms
- INTERVAL: a range in interval values
  -  ex:time interval in clock
- RATIO: data is meaingfully,added,subtracted,multiplies(RATIOS)



    


In [11]:
## numpy
import numpy as np
#dir(np) 

In [5]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.ndim

2

In [7]:
b.shape #no.of elements in array

(2, 3)

In [8]:
b.size

6

In [9]:
b.dtype

dtype('int32')

In [10]:
np.__version__

'1.20.1'

In [12]:
## numpy
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [16]:
b=np.array([[[1,2,3],[4,5,6],[8,9,10],[7,8,9]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [ 7,  8,  9]]])

In [17]:
b.shape

(1, 4, 3)

In [18]:
b.size

12

In [19]:
b.ndim

3

In [20]:
b.dtype

dtype('int32')

In [21]:
# print array starts from 1 to 50 skip by 2
b=np.array(range(1,51,3))
b

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [25]:
a=np.array([1,2,3,4,5])
a[1]

2

In [30]:
## 2dimensionL array
a=np.array([[2,3,4],[8,5,6]])
a[0,2]

4

In [31]:
## n-d arrays
a=np.array([3,4,5,6,7],ndmin=3)
a

array([[[3, 4, 5, 6, 7]]])

In [32]:
## n-d arrays
a=np.array([2,3,4],ndmin=20)
a

array([[[[[[[[[[[[[[[[[[[[2, 3, 4]]]]]]]]]]]]]]]]]]]])

In [35]:
##creating another arrays
i=np.eye(6)
i

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
##null matrics

a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#unit matrix

a=np.ones(5,dtype="int")
a

array([1, 1, 1, 1, 1])

In [44]:
a=np.ones(((3,3,3)))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
a=np.full(5,'hello')
a

array(['hello', 'hello', 'hello', 'hello', 'hello'], dtype='<U5')

In [46]:
a=np.full((3,3),'hello')
a

array([['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello']], dtype='<U5')

In [47]:
a.fill(5)
a

array([['5', '5', '5'],
       ['5', '5', '5'],
       ['5', '5', '5']], dtype='<U5')

In [5]:
##arrange method

import numpy as np
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#constructing 2d array from 1d array

a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
a.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
b=np.arange(100,20,-4)
b

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24])

In [21]:
b.reshape(4,5)


array([[100,  96,  92,  88,  84],
       [ 80,  76,  72,  68,  64],
       [ 60,  56,  52,  48,  44],
       [ 40,  36,  32,  28,  24]])

In [25]:
##RANDOM MODULE

a=np.random.randint(100)
a

48

In [30]:
b=np.random.randint(10,1000)
b

154

In [34]:
lw,uw=int(input()),int(input())
a=np.random.randint(lw,uw,10)
a.reshape(2,5)

6
50


array([[ 6, 21,  8, 47, 39],
       [24, 38, 17, 25, 17]])

In [37]:
b=np.random.random((7,4))
b

array([[0.61546128, 0.86123031, 0.93633226, 0.84818825],
       [0.58103848, 0.67127503, 0.45080879, 0.43764889],
       [0.43007132, 0.54291368, 0.31480405, 0.63338663],
       [0.99703337, 0.49957075, 0.83959359, 0.96234875],
       [0.65644707, 0.8127404 , 0.20045459, 0.47019668],
       [0.78421849, 0.28494221, 0.48463198, 0.50725427],
       [0.39474092, 0.06765408, 0.55878254, 0.32207761]])

In [40]:
c=np.random.randn(4,3)
c


array([[-0.21556064,  0.5493355 , -0.38716182],
       [-0.15413792,  2.06002531,  1.5002513 ],
       [ 0.60627329,  0.26729625,  2.11447662],
       [ 0.40117903,  0.45481286, -0.95836138]])

In [50]:
##LINE SPACE

a=np.linspace(3,5)
a

array([3.        , 3.04081633, 3.08163265, 3.12244898, 3.16326531,
       3.20408163, 3.24489796, 3.28571429, 3.32653061, 3.36734694,
       3.40816327, 3.44897959, 3.48979592, 3.53061224, 3.57142857,
       3.6122449 , 3.65306122, 3.69387755, 3.73469388, 3.7755102 ,
       3.81632653, 3.85714286, 3.89795918, 3.93877551, 3.97959184,
       4.02040816, 4.06122449, 4.10204082, 4.14285714, 4.18367347,
       4.2244898 , 4.26530612, 4.30612245, 4.34693878, 4.3877551 ,
       4.42857143, 4.46938776, 4.51020408, 4.55102041, 4.59183673,
       4.63265306, 4.67346939, 4.71428571, 4.75510204, 4.79591837,
       4.83673469, 4.87755102, 4.91836735, 4.95918367, 5.        ])

In [59]:
##TRANSPOSE

a=np.arange(10).reshape(2,5)
print(a)
print(a.transpose())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [83]:
a=np.arange(20).reshape(4,5)
print(a)
print(a[1,1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[6 7]


## arthemtic operations on arrays

In [93]:
a=np.array([[10,20,30]])
b=np.array([[100,10,10]])
c=a+b
c

array([[110,  30,  40]])

In [98]:
c=a-b
c

array([[-90,  10,  20]])

In [95]:
c=a%b
c

array([[10,  0,  0]], dtype=int32)

In [96]:
c=a/b
c

array([[0.1, 2. , 3. ]])

In [97]:
c=a*b
c

array([[1000,  200,  300]])

In [113]:
## SCIENTIFIC CALCULATIONS
a=np.log([2])
a

array([0.69314718])

In [114]:
a=np.exp([3,4])
a

array([20.08553692, 54.59815003])

In [107]:
a=np.sin([1,2,3])
a

array([0.84147098, 0.90929743, 0.14112001])

In [115]:
# STATICS
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [116]:
print(np.amin(a))


1


In [117]:
print(np.amax(a))

5


In [151]:
a=np.array([[1,5,3],[2,3,4]])
print(np.mean(a))
print(np.median(a))

3.0
3.0


In [152]:
## STANDARD DEVIATION
## square root of avg of square deviation of mean
print(np.std(a))

1.2909944487358056


In [153]:
## VARIANCE
## avg of squares of standard deviation
print(np.var(a))

1.6666666666666667


In [154]:
## AGGREGATION
print(np.sum(a))
print(np.cumsum(a))
print(np.prod(a))
print(np.cumproduct(a))
print(np.all(a))
print(np.any(a))
print(np.min(a),np.max(a))
print(np.argmin(a),np.argmax(a))
print(np.)

18
[ 1  6  9 11 14 18]
360
[  1   5  15  30  90 360]
True
True
1 5
0 1


In [155]:
## FILTERING
a=np.array([20,30,40,50])
f=a>20
n=a[f]
print(f)
print(n)

[False  True  True  True]
[30 40 50]


In [163]:
a=np.array([1,2,3,4,5,6])
f=a%2==0
n=a[f]
print(f)
print(n)

[False  True False  True False  True]
[2 4 6]


In [169]:
## SAVING THE DATA
from numpy import array
from numpy import savetxt
data=np.array([[1,2,3],[5,4,6]])
savetxt('data.csv',data,delimiter=",")

In [170]:
## DIPLAYING THE DATA FROM CSV FILE
from numpy import loadtxt
data=loadtxt('data.csv',delimiter=",")
data

array([[1., 2., 3.],
       [5., 4., 6.]])